# Generated by Django 4.2.3 on 2023-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('about', models.CharField(max_length=90, verbose_name='about')),
                ('full_text', models.TextField(verbose_name='text')),
                ('date', models.DateTimeField(verbose_name='date of making this post')),
            ],
        ),
    ]
